version: '3.8'

services:
  fyne-app:
    build: .
    volumes:
      # Mount screenshots directory to host
      - ./screenshots:/screenshots
      - ./bin:/bin
      - ./books:/books
      # Mount your Fyne app if it's external
      # - ./your-fyne-app:/app/your-fyne-app
    environment:
      - DISPLAY=:99
    ports:
      - "2222:22"  # SSH port
      # If your app needs network access
      # - "8080:8080"
    # Security context for X11
    security_opt:
      - seccomp:unconfined
    # Allocate a tty for proper X11 operation
    tty: true
    stdin_open: true
