created_at = ""
updated_at = ""
version = 0

[[books]]
  title = "Yokai Tales"
  file = "/Users/alexander.king/.0_dotfiles/pennyblack/mock/books/book.epub"
  [books.activity]
    date = ""
    page = 0
    minutes = 0

[[books]]
  title = "Ghost Detective"
  file = "/Users/alexander.king/.0_dotfiles/pennyblack/mock/books/comic-1.cbr"
  [books.activity]
    date = ""
    page = 0
    minutes = 0
